### ISSUE TITLE
Building a tagged llvm version of an already built commit hash skips

### ISSUE THREAD

**Issue by partouf** [compiler-explorer/clang-builder#15]
When trying to build llvm 10.0.1
https://github.com/compiler-explorer/clang-builder/blob/a389cf96c4aff9750c66739abd039a9a6912973d/build/build.sh#L88

```
 VERSION=10.0.1                                                                                                                 [76/1807]
+ [[ 10.0.1 == \t\r\u\n\k ]]                                                                                                              
+ TAG=llvmorg-10.0.1                                                                                                                      
+ URL=https://github.com/llvm/llvm-project.git                                                                                            
+ BRANCH=llvmorg-10.0.1                                                                                                                   
+ REF=refs/heads/llvmorg-10.0.1                                                                                                           
+ [[ ! -z llvmorg-10.0.1 ]]                                                                                                               
+ REF=refs/tags/llvmorg-10.0.1                                                                                                            
++ git ls-remote https://github.com/llvm/llvm-project.git refs/tags/llvmorg-10.0.1                                                        
++ cut -f 1                                                                                                                               
ce-build-revision:llvmorg-69f2239b412aa92f3b857e50945b5dd4c8823ba1-gcc-9.2.0                                                              
ce-build-status:SKIPPED                                                                                                                   
+ LLVMORG_REVISION=69f2239b412aa92f3b857e50945b5dd4c8823ba1                                                                               
+ REVISION=llvmorg-69f2239b412aa92f3b857e50945b5dd4c8823ba1-gcc-9.2.0                                                                     
+ LAST_REVISION=llvmorg-69f2239b412aa92f3b857e50945b5dd4c8823ba1-gcc-9.2.0                                                                
+ echo ce-build-revision:llvmorg-69f2239b412aa92f3b857e50945b5dd4c8823ba1-gcc-9.2.0                                                       
+ [[ llvmorg-69f2239b412aa92f3b857e50945b5dd4c8823ba1-gcc-9.2.0 == \l\l\v\m\o\r\g\-\6\9\f\2\2\3\9\b\4\1\2\a\a\9\2\f\3\b\8\5\7\e\5\0\9\4\5$
b\5\d\d\4\c\8\8\2\3\b\a\1\-\g\c\c\-\9\.\2\.\0 ]]                                                                                          
+ echo ce-build-status:SKIPPED                                                                                                            
+ exit

```

**Comment by partouf** [comment]
For now im gonna copy paste current nightly to 10.0.1

**Comment by apmorton** [comment]
This should be a non-issue if you just don't pass a revision to the build script when running the tagged build (or change the build name so the revision file doesn't exist if copying the admin daily builds script)

**Comment by partouf** [comment]
but I passed clang llvm build.sh llvm 10.0.1 or whatever order

**Comment by partouf** [comment]
it doesn't take into account the version tag when it comes to llvm

**Comment by apmorton** [comment]
`LAST_REVISION="${3}"`

if you don't pass a previous revision to `build.sh`, there is nothing to compare to and it will always build.

The output you show above indicates you copied our `admin-daily-build.sh` and didn't change the build name to prevent _that_ script from reading the revision file.

See comments in slack.

**Comment by partouf** [comment]
I don't think you understand. i get I needed to pass 10.0.1, I did. The problem is that the script does everything right up until it determines the logged version to build. Which only takes into account to commit revision, which totally makes sense! Why build the same thing twice! Except that a tag in git doesn't create a new commit hash, you have a commit hash and it may or not be tagged. In this case, the latest commit and the latest tag were one and the same. I could have waited a day or two and I wouldn't have noticed any of this.

**Comment by apmorton** [comment]
I understand - I'm saying the scripts in this repo _do not have any notion of previously built versions_.

the arguments to `build.sh` are:

```bash
./build.sh "tag_to_build" "/path/to/output.tar.xz" "last_build_revision"
```

`admin-daily-builds.sh` in our infra repo is what handles keeping track of and passing the last_build_revision to this script.
If you _don't_ pass last_build_revision, this script will _ALWAYS_ build.

If you are using the method I showed to build tagged releases where you make a temp copy of `admin-daily-builds.sh`, you just need to make sure you pass in a unique _build name_ (along with the correct tag to build).

```bash
# this will suffer the issue you describe here if the last build has the same commit as the tag given
build_latest clang clang build.sh 10.0.1

# this will always build
build_latest clang clang1001 build.sh 10.0.1
```

Alternatively, if you manually start the builder and run `ce builder exec`, just don't pass anything for the third argument of `build.sh`

```bash
ce builder exec -- \
	sudo docker run --rm --name "clang.build" \
	-v/home/ubuntu/.s3cfg:/root/.s3cfg:ro -e 'LOGSPOUT=ignore' \
	"compilerexplorer/clang-builder" \
        bash build.sh "10.0.1" s3://compiler-explorer/opt/
```

**Comment by partouf** [comment]
It took me a while to see it, but I get it now. It's not super intuitive, but I'm ok with doing it this way next time. Thanks!
