### ISSUE TITLE
llvm master branch is now main

### ISSUE THREAD

**Issue by apmorton** [compiler-explorer/clang-builder#18]
https://lists.llvm.org/pipermail/llvm-dev/2020-November/146615.html

There is a mirror in place until January 7th, at which point the master reference will disappear from llvm/llvm-project

**Comment by apmorton** [comment]
Fixed by abb1251a9ff838987979e067049c07f3ac8f1ee3

**Comment by mattgodbolt** [comment]
oh! thanks! I had a feeling this was somewhere...
