### ISSUE TITLE
SpirV failes to build:

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/clang-builder#29]
```
CMake Error at CMakeLists.txt:76 (MESSAGE):
    llvm-spirv isn't a known project:
    clang;clang-tools-extra;compiler-rt;cross-project-tests;libc;libclc;libcxx;libcxxabi;libunwind;lld;lldb;mlir;openmp;polly;pstl;flang
```

**Comment by mattgodbolt** [comment]
@jzzheng22 do you have any ideas on this? I will re-enable this build to show the error and process we build with.

**Comment by mattgodbolt** [comment]
Example build failure: https://github.com/compiler-explorer/compiler-workflows/runs/4299859849?check_suite_focus=true

**Comment by AnastasiaStulova** [comment]
It seems, that the translator is built as an LLVM subproject but it is currently an independent project... so the instructions for building it in the LLVM tree are documented here: https://github.com/KhronosGroup/SPIRV-LLVM-Translator#llvm-in-tree-build

Has there been any change in godbolt about spirv-llvm build?

**Comment by mattgodbolt** [comment]
Not knowingly, but I'll take another look in case some build refactoring i did broke it! thanks for the hint!

**Comment by AnastasiaStulova** [comment]
Ok, it seems that it was a change in LLVM in Sep:
https://reviews.llvm.org/D110016

So my guess is that we should build llvm-spirv differently now... but I wonder if the instructions in the translator repo are up to dat because they only seem to activate clang in cmake...

**Comment by AnastasiaStulova** [comment]
Looking at the translator build bots it seems that they never set `LLVM_ENABLE_PROJECTS="llvm-spirv"` when building in LLVM tree https://github.com/KhronosGroup/SPIRV-LLVM-Translator/runs/4293773208?check_suite_focus=true.

So I feel if we just drop this option from cmake line then the build will succeed.

**Comment by mattgodbolt** [comment]
Now building!
