### ISSUE TITLE
Failed to build clangbuild docker

### ISSUE THREAD

**Issue by ChuanqiXu9** [compiler-explorer/clang-builder#53]
When I run:

```
sudo docker build -t clangbuilder .
```

in the source tree. The output shows error report:

```
Sending build context to Docker daemon    255kB
Step 1 : ARG image
Please provide a source image with `from` prior to commit
```

It looks like that I need to pass an image argument to it but I don't know how should I pass it.

My docker version is 20.10.6

---

And if I change the DockerFile to

```
# ARG image
FROM ubuntu:22.04
...
```

I received:

```
manifest unknown: OCI index found, but accept header does not support OCI indexes
```

I am on CentOS7.

**Comment by mattgodbolt** [comment]
My apologies this has changed a little and I never explained how!

We build for both 20 and 22; and so one can provide a build-time parameter to choose the base image:

```
$ docker build --build-arg image=22.04 -t clangbuilder .
```

worked for me. Your change to the Dockerfile ought to be equivalent, and on a fresh new computer this worked for me. I will update the README.

Can you post the full output of your build and we can try and diagnose the problem?

**Comment by ChuanqiXu9** [comment]
Thanks for the update and the output in my local environment is:

```
$docker build --build-arg image=22.04 -t clangbuilder .
Sending build context to Docker daemon  95.26MB
Step 1 : ARG image
Please provide a source image with `from` prior to commit
```

It looks like my docker version is not good and it doesn't handle the argument `--build-arg` well.

My docker version is:

```
$docker --version
Docker version 20.10.6, build 370c289
```

So I would try to look at how to update my docker.

**Comment by mattgodbolt** [comment]
That's the same docker version as I haev...curious :(

**Comment by mattgodbolt** [comment]
This is what it looks like when I run locally:
```
mgodbolt-laptop:/t/clang-builder (main|✔) $ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
mgodbolt-laptop:/t/clang-builder (main|✔) $ docker --version
Docker version 20.10.16, build aa7e414
mgodbolt-laptop:/t/clang-builder (main|✔) $ ssh cy2-desktop-129^C
mgodbolt-laptop:/t/clang-builder (main|✔) $ docker build --build-arg image=22.04 -t clangbuilder .
Sending build context to Docker daemon  270.8kB
Step 1/13 : ARG image
Step 2/13 : FROM ubuntu:${image}
 ---> 01f29b872827
Step 3/13 : LABEL MAINTAINER Matt Godbolt <matt@godbolt.org>
 ---> Using cache
 ---> edc037f4aae1
...and so on as it builds...
```

**Comment by mattgodbolt** [comment]
how are you launching `docker` - what is `$docker` ? is it a script of some sort? or is the `$` your prompt?

**Comment by mattgodbolt** [comment]
From your build:
> Sending build context to Docker daemon  95.26MB

This is also very suspicious - there isn't 95MB of data in the repository...I can't imagine what's going on

**Comment by ChuanqiXu9** [comment]
> how are you launching `docker` - what is `$docker` ? is it a script of some sort? or is the `$` your prompt?

Yeah, the `$` marker is the start of the command line. (Maybe the `prompt` in your words).

> This is also very suspicious - there isn't 95MB of data in the repository... I can't imagine what's going on

Yeah, I guess there may be some troubles in my local settings. Since I make it after I change to a brand new machine. I guess it may not make sense to require the docker users to handle such issues. So I'd like to close the issue. Thanks!
